
- name: allow http connection
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    jump: ACCEPT
  notify: iptables save
  become: yes

- name: allow https connection
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 443
    jump: ACCEPT
  notify: iptables save
  become: yes
  when:  is_https_allow  is defined and  is_https_allow 

- name: enable httpd
  systemd:
    name: httpd
    state: started
    enabled: yes
  become: yes

- name: change zabbix apache version 5 to 7
  lineinfile:
    dest: /etc/httpd/conf.d/zabbix.conf
    regexp: 'Ifmodule mod_php'
    line: '    <Ifmodule mod_php7.c>'
  notify: restart httpd
  become: yes

- name: change zabbix apache timezone
  lineinfile:
    dest: /etc/httpd/conf.d/zabbix.conf
    regexp: 'date\.timezone'
    line: '        php_value date.timezone Asia/Tokyo'
  notify: restart httpd
  become: yes


