
##
#

- name: download epel-release
  yum:
    name: https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm
    state: present
  become: yes

- name: delete mariadb
  yum:
    name: mariadb-libs
    state: removed
  become: yes

- name: install mysql
  yum:
    name: ['mysql-community-devel*', 'mysql-community-server*', 'MySQL-python']
    state: present
  become: yes
  
- name: download repo
  yum:
    name: https://repo.zabbix.com/zabbix/4.2/rhel/7/x86_64/zabbix-release-4.2-1.el7.noarch.rpm    
    state: present
  become: yes

- name: install zabbix 
  yum:
    name: ['zabbix-server', 'zabbix-server-mysql', 'zabbix-web-mysql', 'zabbix-agent']
    state: latest
    enablerepo: remi-php73
  become: yes

- name: install apache
  yum:
    name: httpd
    state: latest
  become: yes

- name: install remi repo
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present
  become: yes

- name: remi repo key install
  rpm_key:
    key: http://rpms.famillecollet.com/RPM-GPG-KEY-remi
  become: yes

- name: php 7.3 install
  yum:
    name: php73
    enablerepo: remi
  become: yes

  
